databases:
  - name: gryfn_production
    databaseName: gryfn_production
    user: gryfn

services:
  - type: web
    name: gryfn
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gryfn_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false