class IntakeQuestion < ApplicationRecord
  belongs_to :intake_assessment

    FILE_NAMES =
      %w(
    parliament.mp3
    knapsack.mp3
    foreign.mp3
    litigious.mp3
    ocean.mp3
    intrigue.mp3
    ancient.mp3
    busy.mp3
    heinous.mp3
    achieve.mp3
    zoophyte.mp3
    delight.mp3
    some.mp3
    parturition.mp3
    coulomb.mp3
    couple.mp3
    eager.mp3
    geodesy.mp3
    colloquy.mp3
    father.mp3
    decorate.mp3
    triptych.mp3
    execrable.mp3
    islet.mp3
    does.mp3
    homeopathy.mp3
    risible.mp3
    baby.mp3
    night.mp3
    animal.mp3
    heavy.mp3
    graciously.mp3
    story.mp3
    familiar.mp3
    what.mp3
    aeronautic.mp3
    station.mp3
    mannequin.mp3
    done.mp3
    deny.mp3
    any.mp3
    spectacles.mp3
    funny.mp3
    tomorrow.mp3
    euphony.mp3
    inefficacious.mp3
    malicious.mp3
    doll.mp3
    light.mp3
    toughen.mp3
    gnostic.mp3
    apple.mp3
    bought.mp3
    exiguous.mp3
    clique.mp3
    car.mp3
    vitiate.mp3
    together.mp3
    zealous.mp3
    waltz.mp3
    height.mp3
    trudge.mp3
    call.mp3
    believe.mp3
    league.mp3
    demagogue.mp3
    leitmotif.mp3
    one.mp3
    money.mp3
    listen.mp3
    business.mp3
    decisions.mp3
    emphasize.mp3
    leisure.mp3
    endeavor.mp3
    deliquesce.mp3
    bureau.mp3
    because.mp3
    could.mp3
    city.mp3
    bridge.mp3
    catastrophe.mp3
    laugh.mp3
    dominion.mp3
    enough.mp3
    cautious.mp3
    intermezzo.mp3
    prescription.mp3
    huge.mp3
    tincture.mp3
    prerequisite.mp3
    echo.mp3
    glisten.mp3
    sobriquet.mp3
    liquidate.mp3
    legerdemain.mp3
    egregious.mp3
    know.mp3
    homologous.mp3
    pollute.mp3
    girl.mp3
    do.mp3
    daddy.mp3
    contagious.mp3
    rolled.mp3
    calf.mp3
    there.mp3
    region.mp3
    on.mp3
    conceited.mp3
    mimicry.mp3
    book.mp3
    similar.mp3
    delicious.mp3
    ytterbium.mp3
    regime.mp3
    rough.mp3
    gadget.mp3
    evanesce.mp3
    oligarchy.mp3
    dehiscence.mp3
    malapropos.mp3
    boat.mp3
    above.mp3
    good.mp3
    neighbor.mp3
    was.mp3
    allegiance.mp3
    meadow.mp3
    exonerate.mp3
    rhapsody.mp3
    prairie.mp3
    facsimile.mp3
    campaign.mp3
    they.mp3
    atrocious.mp3
    uncle.mp3
    position.mp3
    sycophant.mp3
    doubt.mp3
    monocotyledon.mp3)

end
